stages:
  - build
  - test

variables:
  MYSQL_DATABASE: nom_de_la_base_de_donnees
  MYSQL_ROOT_PASSWORD: mot_de_passe_root

services:
  - name: mysql:latest
    alias: mysql

build:
  stage: build
  image: php:8.1
  services:
    - mysql:latest
  before_script:
    - apt-get update -yqq
    - apt-get install git unzip -yqq
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - php composer.phar install --no-progress --no-suggest --prefer-dist --optimize-autoloader

test:unit:
  stage: test
  image: php:8.1
  services:
    - mysql:latest
  before_script:
    - apt-get update -yqq
    - apt-get install git unzip -yqq
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - ./vendor/bin/phpunit --testsuite unit

test:functional:
  stage: test
  image: php:8.1
  services:
    - mysql:latest
  before_script:
    - apt-get update -yqq
    - apt-get install git unzip -yqq
    - docker-php-ext-install pdo_mysql
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - ./vendor/bin/phpunit --testsuite functional
